"""
This type stub file was generated by pyright.
"""

class WordData:
    def __init__(self, etymology=..., definitions=..., pronunciations=..., audio_links=...) -> None:
        ...
    
    @property
    def definition_list(self): # -> list[Any]:
        ...
    
    @definition_list.setter
    def definition_list(self, definitions): # -> None:
        ...
    
    def to_json(self): # -> dict[str, Any]:
        ...
    


class Definition:
    def __init__(self, part_of_speech=..., text=..., related_words=..., example_uses=...) -> None:
        ...
    
    @property
    def related_words(self): # -> list[Any]:
        ...
    
    @related_words.setter
    def related_words(self, related_words): # -> None:
        ...
    
    def to_json(self): # -> dict[str, Any]:
        ...
    


class RelatedWord:
    def __init__(self, relationship_type=..., words=...) -> None:
        ...
    
    def to_json(self): # -> dict[str, Any]:
        ...
    


