"""
This type stub file was generated by pyright.
"""

import sys
import warnings
import gi
from gi.repository import GObject, Gtk

"""GUI support for the IPython ZeroMQ kernel - GTK toolkit support.
"""
class GTKEmbed:
    """A class to embed a kernel into the GTK main event loop."""
    def __init__(self, kernel) -> None:
        """Initialize the embed."""
        ...
    
    def start(self): # -> None:
        """Starts the GTK main event loop and sets our kernel startup routine."""
        ...
    
    def iterate_kernel(self): # -> Literal[True]:
        """Run one iteration of the kernel and return True.

        GTK timer functions must return True to be called again, so we make the
        call to :meth:`do_one_iteration` and then return True for GTK.
        """
        ...
    
    def stop(self):
        """Stop the embed."""
        ...
    


