"""
This type stub file was generated by pyright.
"""

import codecs
import os
import pydevd
import socket
import sys
import threading
import debugpy
from debugpy import adapter
from debugpy.common import json, log, sockets
from _pydevd_bundle.pydevd_constants import get_global_debugger
from pydevd_file_utils import absolute_path
from debugpy.common.util import hide_debugpy_internals

_tls = ...
_config = ...
_config_valid_values = ...
_adapter_process = ...
def ensure_logging(): # -> None:
    """Starts logging to log.log_dir, if it hasn't already been done."""
    ...

def log_to(path): # -> None:
    ...

def configure(properties=..., **kwargs): # -> None:
    ...

@_starts_debugging
def listen(address, settrace_kwargs, in_process_debug_adapter=...): # -> tuple[str, int] | None:
    ...

@_starts_debugging
def connect(address, settrace_kwargs, access_token=...): # -> None:
    ...

class wait_for_client:
    def __call__(self): # -> None:
        ...
    
    @staticmethod
    def cancel():
        ...
    


wait_for_client = ...
def is_client_connected():
    ...

def breakpoint(): # -> None:
    ...

def debug_this_thread(): # -> None:
    ...

def trace_this_thread(should_trace): # -> None:
    ...

