"""
This type stub file was generated by pyright.
"""

import abc
from typing import Any

"""Abstract base class for kernel managers."""
class KernelManagerABC(metaclass=abc.ABCMeta):
    """KernelManager ABC.

    The docstrings for this class can be found in the base implementation:

    `jupyter_client.manager.KernelManager`
    """
    @abc.abstractproperty
    def kernel(self) -> Any:
        ...
    
    @abc.abstractmethod
    def start_kernel(self, **kw: Any) -> None:
        """Start the kernel."""
        ...
    
    @abc.abstractmethod
    def shutdown_kernel(self, now: bool = ..., restart: bool = ...) -> None:
        """Shut down the kernel."""
        ...
    
    @abc.abstractmethod
    def restart_kernel(self, now: bool = ..., **kw: Any) -> None:
        """Restart the kernel."""
        ...
    
    @abc.abstractproperty
    def has_kernel(self) -> bool:
        ...
    
    @abc.abstractmethod
    def interrupt_kernel(self) -> None:
        """Interrupt the kernel."""
        ...
    
    @abc.abstractmethod
    def signal_kernel(self, signum: int) -> None:
        """Send a signal to the kernel."""
        ...
    
    @abc.abstractmethod
    def is_alive(self) -> bool:
        """Test whether the kernel is alive."""
        ...
    


