"""
This type stub file was generated by pyright.
"""

from astroid import nodes as astroid_node_classes
from astroid.nodes import BaseContainer, NodeNG

__all__ = ["astroid_node_classes", "NodeNG", "BaseContainer"]
