"""
This type stub file was generated by pyright.
"""

import logging
import comm.base_comm
import traitlets
import traitlets.config
from .comm import Comm

"""Base class to manage comms"""
logger = ...
class CommManager(comm.base_comm.CommManager, traitlets.config.LoggingConfigurable):
    """A comm manager."""
    kernel = ...
    comms = ...
    targets = ...
    def __init__(self, **kwargs) -> None:
        """Initialize the manager."""
        ...
    
    def comm_open(self, stream, ident, msg): # -> None:
        """Handler for comm_open messages"""
        ...
    


