"""
This type stub file was generated by pyright.
"""

from importlib import import_module
from typing import Dict

"""Import basic exposure of libzmq C API as a backend"""
public_api = ...
def select_backend(name: str) -> Dict:
    """Select the pyzmq backend"""
    ...

